apiVersion: v1
kind: Namespace
metadata:
  name: bottegaio-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bottegaio-operator
  namespace: bottegaio-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottegaio-operator
  namespace: bottegaio-operator
spec:
  selector:
    matchLabels:
      app: bottegaio-operator
  template:
    metadata:
      labels:
        app: bottegaio-operator
    spec:
      serviceAccountName: bottegaio-operator
      containers:
      - name: operator
        image: rossonet/bottegaio-operator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bottegaio-operator-admin
subjects:
- kind: ServiceAccount
  name: bottegaio-operator
  namespace: bottegaio-operator
roleRef:
  kind: ClusterRole
  name: bottegaio-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bottegaio-operator
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - deployments
  - services
  - pods
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "bottegaio.com"
  resources:
  - backends
  - backends/status
  - webapps
  - webapps/status
  verbs:
  - '*'
